deploy:
  provider: heroku
  api_key:
    secure: EkjtrVj1noCQ1fLB2sgW73pevym4FWD6G9BjwUKKgRTIcCO0YU/oXSCy57QFNFGLfzfpAF9x8a9L9moJ1cy8287UVKHK+gYm49EwVVatILXd+0VCeZG5E/RI9S2muG5Tg6ppxQHHxWzmup4F6oYEeD5IT9Sx46azDqbIdAhOU1gY2T/tZvitSLDmziYf4hClTmP8GbQigStR0oNOnFTi9tKumD+2e2TvJfNh8qj+mpCCrYvo/7rmUqErIjgbYkhjBcCedF96XXEZ8tv8wemeVj76Y4/e64pY22fsId0UEjXVVren0ovycrIjwyBBAljd8MIP/c94lG18TAs3w51axSKHzqag572fI74tPxKVv9Gu+RHHo/16NIeO73iCM3Jb6TitEOlAmBlMuPJpab7xBGl0mMZHJfcbmUhE1EArbFNqHY78HnhP3owH73nMr/tfWVr4EiW2j8nGO8qzDsQU8rptspy2VaG9ACGk6fFtS+YK+JXD7QybIdS8mihZsRcN6Nzg2bfbHfODHcodtstmTUKylpAY6DVgNPgqEHiETABPlHJEweWDyLYO8ksvb0ornlhOmQuWNXDtT0JfAb1lodLmQ6YBB/jjmsz63xqJVIvq10Wn2ZgGJwhBNJXRGfmEQuy6MU76QpkiaY/TmavPCDeRc09dr/RaFfHo1Du9Geo=
  app: projetnab
  on:
    repo: bigbi01/projet
