# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68eef529ffdc858e856a8451b87a89b6effe75ec26dce27562aa052c367fe3cfa0b9289c83423a560e6692b73abda1cacbc6afcc11d055463cb110436c6c438e

test:
  secret_key_base: a87e177309849d37c8499d339bb6ee3cf7e9b8ea392119aece01b0984541866417093731f4598b9e2dc7d8993a20b7d72169998cb703452dba710912bb021852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
